version: 2

updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    versioning-strategy: lockfile-only
    commit-message:
      prefix: "⬆Composer"
      include: "scope"

  - package-ecosystem: docker
    directory: "/etc/docker/php-fpm"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆Docker"
      include: "scope"

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "⬆Github Actions"
      include: "scope"

