doctrine:
    dbal:
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
        types:
            carbon_interval: GlobalEmergency\Apuntate\Type\CarbonIntervalType
            carbon: Carbon\Doctrine\CarbonType
            serviceStatus: GlobalEmergency\Apuntate\Type\ServiceStatusType
        mapping_types:
            enum: string

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'GlobalEmergency\Apuntate\Entity'
                alias: App
