gesdinet_jwt_refresh_token:
    refresh_token_class: GlobalEmergency\Apuntate\Entity\RefreshToken
    token_parameter_name: refresh_token
    return_expiration: true
    return_expiration_parameter_name: refresh_token_expiration
