#index:
#    path: /
#    controller: GlobalEmergency\Apuntate\Controller\DefaultController::index
login_check:
  path:     /api/auth/login
  methods:  [POST]
  defaults:
    _format: json

gesdinet_jwt_refresh_token:
  path: /api/auth/refresh
  controller: gesdinet.jwtrefreshtoken:refresh
  methods:  [POST]
  defaults:
    _format: json

api_infra_routes:
  resource: ../src/Api/Infrastructure/Symfony/routes.yaml
